# This is a basic workflow to help you get started with Actions

name: Deploy static content

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Connect SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.ADDRESS }}
          username: ${{ secrets.SSHUSER }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd ${{ secrets.REPO }}
            echo Pulling from git
            git pull
            cd ${{ secrets.REPO }}/Backend
            echo Running "npm ci" in Backend
            npm ci
            cd ${{ secrets.REPO }}/Frontend
            echo Running "npm ci" in Frontend
            npm ci
            echo Killing Backend
            pm2 kill
            echo Building Frontend
            npm run build
            cd ${{ secrets.REPO }}/Backend
            echo Restarting backend
            pm2 start npm -- start
            echo Moving Frontend to production
            sudo cp -r ${{ secrets.REPO }}/Frontend/dist/* ${{ secrets.STATIC }}
