# This is a basic workflow to help you get started with Actions

name: Deploy static content

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Connect SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.ADDRESS }}
          username: ${{ secrets.SSHUSER }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd ${{ secrets.REPO }}
            echo Pulling from git
            sleep 2
            git fetch --prune
            git reset --hard origin/main

            cd ${{ secrets.REPO }}/Backend
            echo Killing Backend
            sleep 2
            pm2 kill

            echo Running "npm ci" in Backend
            sleep 2
            if [ -n "$(git diff --name-only HEAD@{1} package-lock.json)" ]; then
              npm ci
            fi

            cd ${{ secrets.REPO }}/Frontend
            echo Running "npm ci" in Frontend
            sleep 2
            if [ -n "$(git diff --name-only HEAD@{1} package-lock.json)" ]; then
              npm ci
            fi


            echo Building Frontend
            sleep 2
            npm run build

            cd ${{ secrets.REPO }}/Backend
            echo Restarting backend
            sleep 2
            pm2 start npm -- start

            echo Moving Frontend to production
            sleep 2
            sudo rsync -av --delete ${{ secrets.REPO }}/Frontend/dist/ ${{ secrets.STATIC }}

            echo Exiting ssh
            sleep 2
            exit 0
